### ISSUE TITLE
[Question] Why choosing Google Cloud Functions over a standalone Express application?

### ISSUE THREAD

**Issue by olivierobert** [hudrucan/google-search-results-react#16]
As part of the assessment of code challenge, we aim to understand the technical picks for the project. Opting for a Serverless solution is part of one of these technical picks. Therefore, we would like to know what made you decide to choose this over something else. 

In addition, how did this choice affect the development process? Did you create the functions first and then build the frontend application? What about the process in local development? 

💡 The README in each project would be a great place to document how other developers can run and use both projects for local development.

**Comment by hudrucan** [comment]
The most important thing when I chosen Serverless or Firebase Functions for the assessment is: It's really fast for development than the another, and it's free, no server management is necessary, inherently scalable,...
The second thing is: I tried to use Google services to access Google search, so I do not need to setting a lot on cloud. One platform for all services of the application.

**Comment by hudrucan** [comment]
I'm working with them at the same time, for example: I finish authentication first on my react app using Firebase Authentication, and then continue to work with serverless for crawling feature. After that finished the react app using Functions above.

**Comment by hudrucan** [comment]
> 💡 The README in each project would be a great place to document how other developers can run and use both projects for local development.

Yeah I knew that, It will be update soon.
