### ISSUE TITLE
[Functionality] The home content is displayed again when a new search is made

### ISSUE THREAD

**Issue by olivierobert** [hudrucan/google-search-results-react#18]
## Issue

After completing a search, if a new search is made the home page content with the project details is displayed again.

## Excepted

The page content should keep the last search content or actually show the list of previously searched keywords.

## Actual

There is a flash of the homepage content:

![2564-09-03 10 53 23](https://user-images.githubusercontent.com/696529/131948407-23fc1aab-69ba-47fb-8843-0692b6ed28e1.gif)

## Steps to reproduce

1. Go to https://search.huynm.dev/import-file
2. Upload one file with numerous keywords
3. Trigger the search and wait for the results to be displayed
4. Trigger the search with the same keywords again

**Comment by hudrucan** [comment]
Fixed issue:
- Keep old results when start to search new keyword list.
- Added options to research current list
- Reverse searched list, newest will be on the top of list

Details related here  #21
