### ISSUE TITLE
[Question] Testing strategy

### ISSUE THREAD

**Issue by olivierobert** [hudrucan/google-search-results-react#20]
While you added unit tests to the other [codebase](https://github.com/hudrucan/google-search-results-functions), none were added for the frontend application. So how do you usually handle testing on such projects?

**Comment by hudrucan** [comment]
Sorry about that, I do not have enough time for writing unit test for all features.

Usually, when I implement a new feature, I tested every thing and make sure it's working right the way I want. After that, if it's stable I will start to write unit test.
